### ISSUE TITLE
LMAO

### ISSUE THREAD

**Issue by Shinyzenith** [evilbryan590/hello-world#2]
WHY AM I LATE TO THIS XD

**Comment by Shinyzenith** [comment]
OMG UR PFP

**Comment by Shinyzenith** [comment]
And yes vimvimvim 

Nyarch best.
Shameless plug https://github.com/xelphlinux

**Comment by evilbryan590** [comment]
AHAHHAHA YUUUUS

**Comment by Shinyzenith** [comment]
XDDD

**Comment by evilbryan590** [comment]
time to just change up my bio...

**Comment by evilbryan590** [comment]
there we go

**Comment by evilbryan590** [comment]
![Reee](https://user-images.githubusercontent.com/62000725/134043157-ca6b204e-794f-43d0-bb1e-c3171f6953ba.jpg)

**Comment by Shinyzenith** [comment]
LMAO BRYAN U MADLAD
