### ISSUE TITLE
pls fix massive bug

### ISSUE THREAD

**Issue by Shinyzenith** [evilbryan590/hello-world#4]
![image](https://user-images.githubusercontent.com/60808802/134422490-d8380ec3-5013-4bf9-968d-b1b438d8ab40.png)

**Comment by Shinyzenith** [comment]
https://guthib.com pls fix, satan wants it fixed

**Comment by evilbryan590** [comment]
fixed 
![image](https://user-images.githubusercontent.com/62000725/134422748-0f2ce7b7-9007-4abb-9205-972b56aeeade.png)

**Comment by evilbryan590** [comment]
all guuchi nyaow

**Comment by Shinyzenith** [comment]
verified fixed, moving to solved board....

**Comment by Shinyzenith** [comment]
task has been closed by satan bot...

**Comment by Shinyzenith** [comment]
best bug fix
